cost_per_vechile = "../datasets/2_kosten_gestapelt_land.csv"
core_data = "../datasets/1_flottenuebersicht_land.csv"
operation_interval_of_vechiles = "../datasets/4_einsaetze_land.csv"
opeartions_hrs_reading_dates = "../datasets/11_messpunkte_land.csv"
number_intensity = "../datasets/5_schocks_gestapelt_land.csv"
